config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, sign_out_via: [:get, :delete]
  resources :employees

  resources :salaries, only: [:index, :show] do
    get 'salary_slip/:month/:year', to: 'salaries#show', on: :collection
  end

  namespace :admin do
    resources :salaries, only: [:create, :update]
    resources :attendances, only: [:index, :create, :update] do
      member do
      patch 'update_attendance'
      end
    end
  end

  resources :investments
  root "home#index"
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user, optional: false, dependent: :destroy  
  has_one :salary, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :investments, dependent: :destroy 
  accepts_nested_attributes_for :salary
  delegate :email, :role, to: :user, allow_nil: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :authenticate_user!
    before_action :authorize_admin, only: [:create, :update, :destroy]
  
    def index
         @employees = Employee.includes(:user).all
    end
      
    def create
      user = User.new(
        email: params[:employee][:email],
        password: "123456",
        password_confirmation: "123456",
        role: params[:employee][:role]
      )
    
      if user.save
        employee = user.create_employee(
          name: params[:employee][:name],
          designation: params[:employee][:designation]
        )
    
        if params[:employee][:salary].present?
          employee.create_salary(
            amount: params[:employee][:salary],
            month: Date.today.month,
            year: Date.today.year
          )
        end
    
        redirect_to employees_path, notice: "Employee Added Successfully"
      else
        Rails.logger.debug "User Save Error: #{user.errors.full_messages}"
        @employees = Employee.includes(:user).all
        @employee = Employee.new
        flash[:alert] = "Error: " + user.errors.full_messages.join(", ")
        render :index
      end
    end
        
    def edit
      @employee = Employee.find(params[:id])
    end
  
    def update
      @employee = Employee.find(params[:id])
      
      current_month = Date.today.month
      current_year = Date.today.year

      if params[:employee][:salary_attributes].present? && !params[:employee][:salary_attributes][:month].present?
        params[:employee][:salary_attributes][:month] = current_month
        params[:employee][:salary_attributes][:year] = current_year
      end
      
      if @employee.update(employee_params)
        redirect_to employees_path, notice: "Employee updated successfully."
      else
        render :edit, status: :unprocessable_entity
      end
    end
    
  
    def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy
      redirect_to employees_path, notice: "Employee Deleted Successfully"
    end
  
    private

    def employee_params
        params.require(:employee).permit(:name, :designation, salary_attributes: [:amount, :month, :year])
      end
      
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<h2>Edit Employee</h2>

<%= form_with(model: @employee, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :designation %>
    <%= form.text_field :designation %>
  </div>

  <div>
    <%= form.fields_for :salary, @employee.salary || @employee.build_salary do |salary_fields| %>
      <%= salary_fields.label :amount %>
      <%= salary_fields.number_field :amount %>
    <% end %>
  </div>

  <div>
    <%= form.submit "Update Employee" %>
  </div>
<% end %>

app/views/employees/index.html.erb
<h2>Manage Employees</h2>

<table border="2" width="100%">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Designation</th>
        <th>Salary</th>
        <th>Actions</th>
    </tr>
    <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.user&.email || "N/A" %></td>  
          <td><%= employee.user&.role || "N/A" %></td>   
          <td><%= employee.designation %></td>
          <td><%= employee.salary&.amount %></td> 
          <td>
            <%= link_to "Edit", edit_employee_path(employee), class: "button" %>
            <%= button_to "Delete", employee_path(employee), method: :delete %>
          </td>
        </tr>
    <% end %>      
</table>

<h3>Add New Employee</h3>
<%= form_with(model: Employee.new, local: true, url: employees_path) do |f| %>
  <p><%= f.label :name %><br><%= f.text_field :name %></p>
  <p><%= f.label :email %><br><%= f.email_field :email %></p>
  <p><%= f.label :designation %><br><%= f.text_field :designation %></p>
  <p><%= f.label :salary %><br><%= f.number_field :salary %></p>
  

  <p><%= f.label :role %><br><%= f.select :role, ["employee", "admin"] %></p>
  <p><%= f.submit "Add Employee", class: "button" %></p>
<% end %>