config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, sign_out_via: [:get, :delete]
  resources :employees

  resources :salaries, only: [:index, :show] do
    get 'salary_slip/:month/:year', to: 'salaries#show', on: :collection
  end

  namespace :admin do
    resources :salaries, only: [:create, :update]
    resources :attendances, only: [:index, :create, :update] do
      member do
      patch 'update_attendance'
      end
    end
  end

  resources :investments
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <h2>Welcome to Payroll Management System!</h2>

  <% if current_user %>
    <p>Logged in as: <%= current_user.email %> (Role: <%= current_user.role %>)</p>

    <% if current_user.admin? %>
      <h3>We made it easy to manage your employees:</h3>
      <ul>
  <li>✅ <%= link_to "Manage Employees", employees_path %></li>
  <li>✅ <%= link_to "Manage Salaries", admin_salaries_path %></li>
  <li>✅ <%= link_to "Manage Attendance", admin_attendances_path %></li>
</ul>


    <% elsif current_user.employee? %>
      <h3>We made it easy to manage your:</h3>
      <ul>
        <li>✅ <%= link_to "Your Investments", investments_path %></li>
        <li>✅ <%= link_to "Your Salary Slip", salaries_path %></li>
      </ul>

    <% else %>
      <p>Unknown role detected. Please contact Admin to update your user role.</p>
    <% end %>

  <% else %>
    <p>You are not logged in.</p>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>